#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent

set -e

echo "========================================"
echo "Starting Development Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# START SERVICES
# ============================================

# Main Application (Astro + React)
echo "Starting main application..."
cd /Users/jake/workspace/action-amp
npm run dev &
MAIN_PID=$!

wait_for_service 3000 "Main Application"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  Main Application: http://localhost:3000"
echo ""
echo "WorkLab Feature:"
echo "  - Navigation will be available at: http://localhost:3000"
echo "  - WorkLab page will be at: http://localhost:3000/worklab"
echo ""
echo "To stop services:"
echo "  kill $MAIN_PID"
echo ""