#!/usr/bin/env bash
# One-time setup for isolated e2e via git worktree.
#
# Creates a sibling worktree with its own .wasp/, a separate e2e database on
# the existing Postgres server, and env files. After this, `npm run
# test:e2e:isolated` in the worktree runs side-by-side with dev — no port or
# .wasp/ collisions, same PG server, different database.
#
# Run from anywhere in the main checkout:
#   bash webapp/scripts/e2e-setup.sh
#
# Config (override via env if your setup differs):
#   E2E_PG_USER  (default: jake)
#   E2E_PG_HOST  (default: localhost)
#   E2E_PG_PORT  (default: 5432)
set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
WORKTREE_DIR="$REPO_ROOT/../action-amp-e2e"
PG_USER="${E2E_PG_USER:-jake}"
PG_HOST="${E2E_PG_HOST:-localhost}"
PG_PORT="${E2E_PG_PORT:-5432}"
E2E_DB="actionamp_e2e"

# Locate psql — Homebrew keg-only postgresql@18 isn't on PATH by default.
PSQL="$(command -v psql 2>/dev/null || true)"
if [ -z "$PSQL" ]; then
  for cand in \
    /opt/homebrew/opt/postgresql@18/bin/psql \
    /opt/homebrew/opt/postgresql@17/bin/psql \
    /opt/homebrew/opt/postgresql@16/bin/psql \
    /opt/homebrew/opt/libpq/bin/psql \
    /usr/local/opt/postgresql/bin/psql \
    /Applications/Postgres.app/Contents/Versions/latest/bin/psql; do
    if [ -x "$cand" ]; then PSQL="$cand"; break; fi
  done
fi
if [ -z "$PSQL" ]; then
  echo "ERROR: psql not found. Install postgresql client tools or set \$PSQL." >&2
  exit 1
fi
echo "Using psql: $PSQL"

ADMIN_URL="postgresql://$PG_USER@$PG_HOST:$PG_PORT/postgres"

# 1. Create git worktree (sibling dir, own .wasp/).
#    Can't checkout `main` — it's already checked out in the main worktree.
#    -B e2e creates (or resets) a dedicated e2e branch at main's HEAD. Re-running
#    this script re-syncs the worktree to main; gitignored env files survive.
if [ -d "$WORKTREE_DIR" ]; then
  echo "Worktree already exists at $WORKTREE_DIR — syncing to main"
  git -C "$WORKTREE_DIR" fetch origin main 2>/dev/null || true
  git -C "$WORKTREE_DIR" reset --hard main
else
  git worktree add -B e2e "$WORKTREE_DIR" main
  echo "Created worktree at $WORKTREE_DIR (branch: e2e, tracking main)"
fi

# 2. Create e2e database on existing PG server (same :5432, different DB).
if "$PSQL" "$ADMIN_URL" -tAc "SELECT 1 FROM pg_database WHERE datname='$E2E_DB'" | grep -q 1; then
  echo "Database $E2E_DB already exists"
else
  "$PSQL" "$ADMIN_URL" -c "CREATE DATABASE $E2E_DB"
  echo "Created database $E2E_DB"
fi

# 3. Write .env.server (server boot vars — dummy SMTP is fine for e2e, no test
#    sends real email; the Zod schema just requires non-empty values).
cat > "$WORKTREE_DIR/webapp/.env.server" <<EOF
# E2E worktree env — auto-generated by scripts/e2e-setup.sh.
# Dummy SMTP values satisfy the boot-time Zod schema; no e2e test sends email.
DATABASE_URL=postgresql://$PG_USER@$PG_HOST:$PG_PORT/$E2E_DB
WASP_WEB_CLIENT_URL=http://localhost:4100
WASP_SERVER_URL=http://localhost:3101
PORT=3101
SKIP_EMAIL_VERIFICATION_IN_DEV=true
SMTP_HOST=localhost
SMTP_PORT=1025
SMTP_USERNAME=dummy
SMTP_PASSWORD=dummy
EOF

# 4. Write .env.client (client API URL so the client talks to the e2e server).
cat > "$WORKTREE_DIR/webapp/.env.client" <<EOF
# E2E worktree env — auto-generated.
REACT_APP_API_URL=http://localhost:3101
EOF

# 5. Write .e2e.env (loaded by playwright.config.ts to activate isolated mode).
cat > "$WORKTREE_DIR/webapp/.e2e.env" <<EOF
# E2E worktree env — auto-generated, gitignored.
E2E_WORKTREE=1
E2E_BASE_URL=http://localhost:4100
E2E_DATABASE_URL=postgresql://$PG_USER@$PG_HOST:$PG_PORT/$E2E_DB
VITE_PORT=4100
EOF

# 6. Install deps FIRST — wasp db migrate-dev needs node_modules present.
#    The worktree has its own node_modules; .wasp/spec/ is generated by wasp.
cd "$WORKTREE_DIR/webapp"
echo "Installing deps..."
wasp install

# 7. Compile + migrate (creates .wasp/ structure, applies schema to e2e DB).
#    `--name auto` avoids Prisma's interactive prompt.
echo "Compiling + migrating e2e DB..."
wasp db migrate-dev --name auto

echo ""
echo "✓ Setup complete. To run isolated e2e:"
echo "  cd $WORKTREE_DIR/webapp && npm run test:e2e:isolated"
echo ""
echo "  Dev server in the main checkout continues on :4000 — no conflict."
