// ponytail: Google auth disabled in main.wasp.ts. `googleSignInUrl` is only
// generated by Wasp when the google provider is enabled, so this file is
// stubbed out until re-enablement. To restore: uncomment the import + body
// below and re-add <GoogleButton /> to Login/Signup pages. See main.wasp.ts.
// import { googleSignInUrl } from "wasp/client/auth";

/**
 * "Continue with Google" button for the login + signup pages.
 *
 * Uses Wasp's generated `googleSignInUrl` (the OAuth start URL) rather than a
 * hand-rolled OAuth flow — Wasp handles the redirect/callback/session. Rendered
 * as a plain anchor styled to sit above the email form, matching AuthLayout
 * tokens.
 *
 * Why custom (not Wasp's stock `GoogleSignInButton`)? The stock button ships its
 * own `SocialButton` styles that don't match our `--aa-*` design tokens; this
 * re-skin reuses the same `googleSignInUrl` from the SDK but renders it in our
 * AuthLayout card. It is NOT a hand-rolled OAuth flow — same URL, our chrome.
 *
 * Note: `googleSignInUrl` is a plain string constant built synchronously from
 * `config.apiUrl` (`${apiUrl}/auth/google/login`) — it is never null. If Google
 * OAuth is misconfigured server-side, the click still navigates to the login
 * URL and the server returns the error. That's the honest behavior; we don't
 * fake a disabled state.
 */
export function GoogleButton({ label = "Continue with Google" }: { label?: string }) {
  // ponytail: disabled — see file-top note.
  void label;
  return null;
  /* eslint-disable */
  /* // original body — restored when Google auth is re-enabled in main.wasp.ts:
  return (
    <a
      className="aa-auth-google"
      href={googleSignInUrl}
      aria-label={label}
    >
      <GoogleGlyph />
      <span>{label}</span>
    </a>
  );
  */
}

/** The standard 4-color Google "G". Inline SVG so we don't add an asset dep.
 *  The 4 hex colors are Google's official brand mark (a recognized third-party
 *  logo), not decorative color — the exception to "color must carry meaning." */
function GoogleGlyph() {
  return (
    <svg width="18" height="18" viewBox="0 0 18 18" aria-hidden="true">
      <path
        fill="#4285F4"
        d="M17.64 9.2c0-.637-.057-1.251-.164-1.84H9v3.481h4.844a4.14 4.14 0 0 1-1.796 2.716v2.259h2.908c1.702-1.567 2.684-3.875 2.684-6.615z"
      />
      <path
        fill="#34A853"
        d="M9 18c2.43 0 4.467-.806 5.956-2.18l-2.908-2.259c-.806.54-1.837.86-3.048.86-2.344 0-4.328-1.583-5.036-3.711H.957v2.332A8.997 8.997 0 0 0 9 18z"
      />
      <path
        fill="#FBBC05"
        d="M3.964 10.71A5.41 5.41 0 0 1 3.682 9c0-.593.102-1.17.282-1.71V4.958H.957A8.996 8.996 0 0 0 0 9c0 1.452.348 2.827.957 4.042l3.007-2.332z"
      />
      <path
        fill="#EA4335"
        d="M9 3.58c1.321 0 2.508.454 3.44 1.345l2.582-2.58C13.463.891 11.426 0 9 0A8.997 8.997 0 0 0 .957 4.958L3.964 7.29C4.672 5.163 6.656 3.58 9 3.58z"
      />
    </svg>
  );
}
